{% set name = "rio-tiler" %}
{% set version = "7.5.1" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rio_tiler-{{ version }}.tar.gz
  sha256: d81fdb5dc9a1460f18cb084523a62eff8d8f62eaa2f9f8e4feee80dfa1f98a8b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - affine
    - attrs
    - cachetools
    - httpx
    - numexpr
    - numpy
    - morecantile >=5.0,<7.0
    - pydantic ~=2.0
    - pystac >=0.5.4
    - rasterio >=1.3.0
    - color-operations
    - importlib-resources >=1.1.0

test:
  imports:
    - rio_tiler
    - rio_tiler.cmap_data
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cogeotiff/rio-tiler
  summary: User friendly Rasterio plugin to read raster datasets.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AndrewAnnex
    - jsignell
    - lsetiawan
    - nrweir
