{% set name = "rio-tiler" %}
{% set version = "8.0.0" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rio_tiler-{{ version }}.tar.gz
  sha256: dccbfdcf61c9bdd34182e6a3f3fe9fe2d936ab6dd3faab99f461d599a1f04147

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - attrs
    - cachetools
    - httpx
    - numexpr
    - numpy
    - morecantile >=5.0,<8.0
    - pydantic ~=2.0
    - pystac >=1.9,<2.0
    - rasterio >=1.4.0
    - color-operations

test:
  imports:
    - rio_tiler
    - rio_tiler.cmap_data
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cogeotiff/rio-tiler
  summary: User friendly Rasterio plugin to read raster datasets.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AndrewAnnex
    - jsignell
    - lsetiawan
    - nrweir
