{% set name = "rio-tiler" %}
{% set version = "4.1.11" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rio_tiler-{{ version }}.tar.gz
  sha256: c8a81011c551678d6d7bbe1c0991770af2335b10865c07b3a6f4eb52c1a73e3a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - attrs
    - boto3
    - cachetools
    - httpx
    - numexpr
    - numpy
    - morecantile >=3.1,<4.0
    - pydantic
    - pystac >=0.5.4
    - rasterio >=1.3.0
    - color-operations
    - importlib-resources >=1.1.0

test:
  imports:
    - rio_tiler
    - rio_tiler.cmap_data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cogeotiff/rio-tiler
  summary: User friendly Rasterio plugin to read raster datasets.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jsignell
    - lsetiawan
    - nrweir
